version: "3.0"

services:
  postgres:
    image: "postgres:13.1"
    container_name: "newone-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "newone"
      POSTGRES_PASSWORD: "newone!"
    volumes:
      - newone-postgres-data:/var/lib/postgresql/data
      
volumes:
  newone-postgres-data:
    external: true